### ISSUE TITLE
Visibility/Semantics of Instantaneous Actions

### ISSUE THREAD

**Issue by howell** [tonyg/prospect#13]
```racket
#lang prospect

(require prospect/actor)

(struct thing (it) #:transparent)

(actor
 (forever
  (on (asserted (thing $it))
      (printf "asserted ~v\n" it))
  (on (retracted (thing $it))
      (printf "retracted ~v\n" it))))

(actor
 (assert! (thing 1))
 (retract! (thing 1))
 (assert! (thing 1)))
```

I'm not sure what the semantics of this should be, but I do think it should end with `(thing 1)` being asserted. Currently, running it produces

```
asserted 1
retracted 1
```

**Comment by tonyg** [comment]
Ah, I see what is happening.

The last actor there is exiting, which causes its assertions to be retracted. Writing this in its place leads to just "asserted 1" being produced:

```racket
(actor
 (assert! (thing 1))
 (retract! (thing 1))
 (assert! (thing 1))
 (forever))
```

So it is still bundling up partial patches, and we still have a design question to think about (should it bundle patches? should it "yield" or continue doing what it's doing now which is carry on until it runs out of stuff to do?), but at least I don't have a fundamental bug in the patch-calculation code :-)
